### ISSUE TITLE
Create Function for Creating an Order

### ISSUE THREAD

**Issue by Peikii** [CSCI-GA-2820-FA22-001/orders#1]
**As a** user
**I need** a function for creating an order
**So that** I am able to create a new order

**Details & Assumptions:** 
* When I click "Make an order", it will take all the information related to the current order and create an order on my side

**Acceptance Criteria:**

```gherkin
When we call 'POST /orders'
Then an instance of Orders is established
```

**Comment by Hui606** [comment]
Need to use some **specific item** to replace "resource"
