### ISSUE TITLE
Create API for Querying Specific Item in a Specific Order

### ISSUE THREAD

**Issue by li928904115** [CSCI-GA-2820-FA22-001/orders#13]
**As a** user  
**I need** the functionality of querying items in a specific order
**So that** I can check the details of an item in a specific order

**Details & Assumptions:** 
* Each order has a unique order id.
* I sign in with my username and password.

**Acceptance Criteria:**

```gherkin
Given that I made an order with id = 123 that contains item {id}
When I call 'GET /orders/123/items/{id}'
Then I should see the details of that item in that specific order shown on the webpage
```

**Comment by RealChanandlerBong** [comment]
The title is not consistent with the detail. The title says 'items' while the details refers to one single item in an order.
