### ISSUE TITLE
Create API for Listing items in an Order

### ISSUE THREAD

**Issue by RealChanandlerBong** [CSCI-GA-2820-FA22-001/orders#15]
**As a** user
**I need** some function to view all items in an order 
**So that** I can know what is included in the order

**Details & Assumptions:** 
* Each order has an unique ID

**Acceptance Criteria:**

```gherkin
When I call 'POST /orders'
It creates an order and return its ID
Then I call 'POST /orders/{id}/item'
It adds some item to the order
Then I call 'GET /orders/{id}/items'
It should return the item that I just added
```

**Comment by Vrbitko** [comment]
Hello, can I take this issue?
